package com.sh.wm.ministry.featuers.userfile.incubatorsAndInstitueBenefit.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class SupportingInstitute {

    @SerializedName("BENEFICIARY_USER_ID")
    @Expose
    private String bENEFICIARYUSERID;
    @SerializedName("BENEFICIARY_PROJECT_ID")
    @Expose
    private String bENEFICIARYPROJECTID;
    @SerializedName("BENEFICIARY_PROJECT_FUNDING_INSTIUTION_ID")
    @Expose
    private String bENEFICIARYPROJECTFUNDINGINSTIUTIONID;
    @SerializedName("BENEFICIARY_PROJECT_TITLE")
    @Expose
    private String bENEFICIARYPROJECTTITLE;
    @SerializedName("BENEFICIARY_PROJECT_LABOR_SECTOR_ID")
    @Expose
    private String bENEFICIARYPROJECTLABORSECTORID;
    @SerializedName("BENEFICIARY_PROJECT_START_DATE")
    @Expose
    private String bENEFICIARYPROJECTSTARTDATE;
    @SerializedName("SUPPORTING_INSTITUATION_NAME")
    @Expose
    private String sUPPORTINGINSTITUATIONNAME;

    public String getBENEFICIARYUSERID() {
        return bENEFICIARYUSERID;
    }

    public void setBENEFICIARYUSERID(String bENEFICIARYUSERID) {
        this.bENEFICIARYUSERID = bENEFICIARYUSERID;
    }

    public String getBENEFICIARYPROJECTID() {
        return bENEFICIARYPROJECTID;
    }

    public void setBENEFICIARYPROJECTID(String bENEFICIARYPROJECTID) {
        this.bENEFICIARYPROJECTID = bENEFICIARYPROJECTID;
    }

    public String getBENEFICIARYPROJECTFUNDINGINSTIUTIONID() {
        return bENEFICIARYPROJECTFUNDINGINSTIUTIONID;
    }

    public void setBENEFICIARYPROJECTFUNDINGINSTIUTIONID(String bENEFICIARYPROJECTFUNDINGINSTIUTIONID) {
        this.bENEFICIARYPROJECTFUNDINGINSTIUTIONID = bENEFICIARYPROJECTFUNDINGINSTIUTIONID;
    }

    public String getBENEFICIARYPROJECTTITLE() {
        return bENEFICIARYPROJECTTITLE;
    }

    public void setBENEFICIARYPROJECTTITLE(String bENEFICIARYPROJECTTITLE) {
        this.bENEFICIARYPROJECTTITLE = bENEFICIARYPROJECTTITLE;
    }

    public String getBENEFICIARYPROJECTLABORSECTORID() {
        return bENEFICIARYPROJECTLABORSECTORID;
    }

    public void setBENEFICIARYPROJECTLABORSECTORID(String bENEFICIARYPROJECTLABORSECTORID) {
        this.bENEFICIARYPROJECTLABORSECTORID = bENEFICIARYPROJECTLABORSECTORID;
    }

    public String getBENEFICIARYPROJECTSTARTDATE() {
        return bENEFICIARYPROJECTSTARTDATE;
    }

    public void setBENEFICIARYPROJECTSTARTDATE(String bENEFICIARYPROJECTSTARTDATE) {
        this.bENEFICIARYPROJECTSTARTDATE = bENEFICIARYPROJECTSTARTDATE;
    }

    public String getSUPPORTINGINSTITUATIONNAME() {
        return sUPPORTINGINSTITUATIONNAME;
    }

    public void setSUPPORTINGINSTITUATIONNAME(String sUPPORTINGINSTITUATIONNAME) {
        this.sUPPORTINGINSTITUATIONNAME = sUPPORTINGINSTITUATIONNAME;
    }
}
